config/routes.rb
Rails.application.routes.draw do
  resources :people
  devise_for :users
  	# get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'people#index'
   #root 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?



  protected
  

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :country,:sport,  :email, :remember_me]) 
  	devise_parameter_sanitizer.permit(:sign_in, keys:[:password,  :email, :remember_me]) 
  	devise_parameter_sanitizer.permit(:account_update , keys: [:name, :age,:country, :sport,  :email, :remember_me] ) 
  	#devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :age, :sport, :password,  :email, :remember_me)}

  end


end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
    @person = Person.new
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :country, :sport, :age)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  		@users  = User.all
  		 
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

def destroy
   session[:user_id] = nil
  #  redirect_to root_url, notice: 'Logged out!' 
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
	  :user
	end

	def resource
	  @resource ||= User.new
	  
	end

	def devise_mapping
	  @devise_mapping ||= Devise.mappings[:user]
	end

	def resource_class
	  devise_mapping.to

	end
	

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pappcorn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <header>
  	<div class="text-center text-wite ">
  		
  		PRUEBA PAPPCORN
  	</div>
  </header>


    <%= yield %>

 	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <footer class="text-center text-wite">
    	<i></i> 2017 Andres Rojas  - Prueba PappCorn 2017

    </footer>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name ,:class=> "form-control"%>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country,:class=> "form-control" %>
  </div>

  <div class="field">
    <%= f.label :sport %>
    <%= f.text_field :sport,:class=> "form-control" %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age,:class=> "form-control" %>
  </div>
<br>
  <div class="actions text-center">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-sm-2"></div>
<div class="col-sm-8">
  
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>Sport</th>
      <th>Age</th>
      <th></th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.country %></td>
        <td><%= person.sport %></td>
        <td><%= person.age %></td>
       <!-- <td><%= link_to 'Show', person %></td>-->
        <td><%= link_to ( edit_person_path(person)) do  %>
        <span class="btn-edit"></span>
          <% end %>
        </td>
        <td><%= link_to ( person ),  method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="btn-delete"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="col-sm-2"></div>

</div>
<div id="myModal" style="">
  <i class="ion-person-add" style="color:#fff; font-size: 40px;"></i>
</div>
<br><br><br><br><br><br><br><br><br><br>
<!--
<%= link_to (  new_person_path) do %>
<div style="position:fixed; bottom: 100px; right:100px; background:#333; padding:10px 23px; border-radius: 100px;cursor: pointer">
  <i class="ion-person-add" style="color:#fff; font-size: 40px;"></i>
</div>
<% end %>
-->


<div class="modal fade" tabindex="-1" role="dialog" id="newRegistration">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" style="color:#fff;     width: 100%;">Modal title</h4>
      </div>
      <div class="modal-body">
      <div class="row">
      <div class="col-sm-12">
        <%= render 'form', person: @person %>
      </div>
       
       </div>
      </div>
      <!--<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>-->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
  
  $('#myModal').on('click', function () {
 
  $('#newRegistration').modal('show');
});
</script>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @person.country %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @person.sport %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<div>&nbsp;</div>
<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<table class="table table-striped">	
			<thead>
			<tr>
				<th>
					ID
				</th>
				<th>
					País
				</th>
				<th>
					Nombre
				</th>
				<th>
					Deportes
				</th>
				<th>
					Edad
				</th>
				<th>
					Borrar
				</th>
				<th>
					Editar
				</th>
				</tr>
			</thead>
			<tbody>

				<% @users.each do |user| %>

				<tr>
					
					<td><%= user %></td>
					
					<td><%= user.country %></td>
					<td><%= user.name %></td>
					<td><%= user.sport %></td>
					<td><%= user.age %></td>
					<td><%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></td>
					<td><%= link_to "Change your password", edit_user_registration_path %></td>
					<td></td>
				</tr>

			<% end %>

				

			</tbody>

		</table>
	</div>
	<div class="col-sm-2"></div>
</div>

			